application: skipflog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /app
  static_dir: app

- url: /ranking
  script: main.app
  login: admin
  
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
