application: skipflog
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /app
  static_dir: app

- url: /ranking
  script: main2.app
  login: admin
  
- url: /.*
  script: main2.app

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
